### PR TITLE
Fix/upload issue

### LINKED ISSUE #578: Consensus on writemarker lock
We ask writemarker lock with the blobber. All the failing blobbers should be removed from the upload mask, and upload should be made only to the succeeding blobbers. Consensus should be calculated on the number of locks acquired.

**_Note: All the blobbers should be requested for the lock_**

We don't have any reason to use `resty` client. So modify it to commonly used http client from zboxcli utils.

### PR DESCRIPTION
**Pull request by lpoli**
### Changes
This PR has solved multiple issues.
1. Change consensus field type to int to make calculation dead simple and elegant.
2. Add `data+1` successful blobbers for consensus ok and `data` if parity is 0.
3. Replace `resty`  with normal http client for http communications.
4. Fix unit tests accordingly.
5. Make `mask` type consistent. All `mask` has type `zboxutil.Uint128`.
6. Close http response body for connection re-use.

### Fixes
-

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/upload-issue  |
| gosdk  | fix/upload-issue  |
| zboxcli  | fix/upload-issue  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/rate-limiter  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | fix/upload-issue  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

File: zboxcore/sdk/chunked_upload.go [hunk 1]
```diff
@@ -521,31 +546,34 @@ func (su *ChunkedUpload) processUpload(chunkStartIndex, chunkEndIndex int, fileS
...
 			return err
 		}
 
-		go func(b *ChunkedUploadBlobber, buf *bytes.Buffer, form ChunkedUploadFormMetadata) {
-			err := b.sendUploadRequest(ctx, su, chunkEndIndex, isFinal, encryptedKey, buf, form)
-
-			// channel is not closed
-			if ctx.Err() == nil {
-				wait <- err
+		su.wg.Add(1)
```
Comment (peterlimg) [inline zboxcore/sdk/chunked_upload.go]: Instead of using the sharded one of `su.wg`, it would be safer to define and use wait group here as `wg := sync.WaitGroup{}` . If the `su.wg`  was used in other places concurrently, the `su.wg.Wait()` would have to wait for all of the others to be done as well, which is not necessary and should be avoid.

File: zboxcore/sdk/chunked_upload.go [hunk 2]
```diff
@@ -578,40 +595,32 @@ func (su *ChunkedUpload) processCommit() error {
 
 		blobber.commitChanges = append(blobber.commitChanges, su.buildChange(blobber.fileRef))
 
-		go func(b *ChunkedUploadBlobber) {
-			err := b.processCommit(ctx, su)
-
+		su.wg.Add(1)
```
Comment (peterlimg) [inline zboxcore/sdk/chunked_upload.go]: same as above, we should avoid using sharded `su.wg`

File: zboxcore/sdk/chunked_upload_blobber.go [hunk 3]
```diff
@@ -61,42 +76,59 @@ func (sb *ChunkedUploadBlobber) sendUploadRequest(ctx context.Context, su *Chunk
...
-	resp, err := su.client.Do(req.WithContext(ctx))
+	var resp *http.Response
+	for i := 0; i < 3; i++ {
 
-	if err != nil {
-		logger.Logger.Error("Upload : ", err)
-		return err
-	}
-	defer resp.Body.Close()
+		if resp != nil {
```
Comment (peterlimg) [inline zboxcore/sdk/chunked_upload_blobber.go]: Wrap the code in the for loop into a anonymous function to make it easier to manage the `defer` code for the `resp.Body` and `ctxCncl`.

File: zboxcore/sdk/chunked_upload_blobber.go [hunk 4]
```diff
@@ -182,38 +225,55 @@ func (sb *ChunkedUploadBlobber) processCommit(ctx context.Context, su *ChunkedUp
 
 	logger.Logger.Info("Committing to blobber." + sb.blobber.Baseurl)
 
-	//for retries := 0; retries < 3; retries++ {
+	var resp *http.Response
+	for retries := 0; retries < 3; retries++ {
+		if resp != nil {
```
Comment (peterlimg) [inline zboxcore/sdk/chunked_upload_blobber.go]: Same as above

File: zboxcore/sdk/consensus.go [hunk 5]
```diff
@@ -5,71 +5,42 @@ import (
...
-	consensus       float32 // Total successful and valid response from blobbers
-	consensusThresh float32 // Consensus threshold percentage
-	fullconsensus   float32 // Total number of blobbers in allocation
-	// Total successful and valid responses required from blobbers. Usually its a.DataShards + 1 but if number of parity-shards is 0 then
-	// it is a.DataShards. Current implements adds 10 percent as additional percentage to consensusThreshold
-	consensusRequiredForOk float32
+	mu              *sync.RWMutex
+	consensus       int // Total successful and valid response from blobbers
+	consensusThresh int // Consensus threshold percentage
+	fullconsensus   int // Total number of blobbers in allocation
```
Comment (peterlimg) [inline zboxcore/sdk/consensus.go:11]: Let's not repeat the word of 'consensus'. Instead of seeing `consensus.consensusThresh`, it would be better to have `consensus.threshold`. So perhaps use `num`, `threshold`, `full` for the variables above.

File: zboxcore/sdk/copyworker.go [hunk 6]
```diff
@@ -32,7 +32,8 @@ type CopyRequest struct {
 	destPath       string
 	ctx            context.Context
 	wg             *sync.WaitGroup
-	copyMask       uint32
+	copyMask       zboxutil.Uint128
+	maskMU         *sync.Mutex
```
Comment (peterlimg) [inline zboxcore/sdk/copyworker.go:35]: Perhaps wrap the mask with mutex to a struct and implement methods to set/unset bits to make it easy to be reused.

File: zboxcore/sdk/copyworker.go [hunk 7]
```diff
@@ -41,107 +42,148 @@ func (req *CopyRequest) getObjectTreeFromBlobber(blobber *blockchain.StorageNode
...
+	blobber *blockchain.StorageNode, blobberIdx int) (refEntity fileref.RefEntity, err error) {
+
+	defer req.wg.Done()
+
+	defer func() {
+		if err != nil {
+			req.maskMU.Lock()
+			// Removing blobber from mask
+			req.copyMask = req.copyMask.And(zboxutil.NewUint128(1).Lsh(uint64(blobberIdx)).Not())
+			req.maskMU.Unlock()
```
Comment (peterlimg) [inline zboxcore/sdk/copyworker.go:54]: As suggested above, the mask actions could be wrapped up

File: zboxcore/sdk/copyworker.go [hunk 8]
```diff
@@ -41,107 +42,148 @@ func (req *CopyRequest) getObjectTreeFromBlobber(blobber *blockchain.StorageNode
...
 			}
+			time.Sleep(time.Duration(r) * time.Second)
+			continue
 		}
-		return nil
-	})
-	if err != nil {
-		return nil, err
+		l.Logger.Error(blobber.Baseurl, "Response: ", string(respBody))
+		err = errors.New("response_error", string(respBody))
```
Comment (peterlimg) [inline zboxcore/sdk/copyworker.go]: Should we retry if the error is not TooManyRequest? Seems the logic is different from the one in chunked_upload_blobber.go

File: zboxcore/sdk/copyworker.go [hunk 9]
```diff
@@ -41,107 +42,148 @@ func (req *CopyRequest) getObjectTreeFromBlobber(blobber *blockchain.StorageNode
...
 	req.wg = &sync.WaitGroup{}
 	req.wg.Add(numList)
-	for i := 0; i < numList; i++ {
+
+	var pos uint64
+	for i := req.copyMask; !i.Equals64(0); i = i.And(zboxutil.NewUint128(1).Lsh(pos).Not()) {
+		pos = uint64(i.TrailingZeros())
 		go func(blobberIdx int) {
-			defer req.wg.Done()
 			refEntity, err := req.copyBlobberObject(req.blobbers[blobberIdx], blobberIdx)
```
Comment (peterlimg) [inline zboxcore/sdk/copyworker.go]: wg.Done is not called. Again, the wg should not be shared, we would not gain anything but potential longer waiting.

File: zboxcore/sdk/deleteworker.go [hunk 10]
```diff
@@ -49,56 +62,91 @@ func (req *DeleteRequest) deleteBlobberFile(blobber *blockchain.StorageNode, blo
...
+		cncl()
+
 		if err != nil {
-			l.Logger.Error("Delete : ", err)
-			return err
+			logger.Logger.Error(blobber.Baseurl, "Delete: ", err)
+			return
 		}
+
 		defer resp.Body.Close()
```
Comment (peterlimg) [inline zboxcore/sdk/deleteworker.go]: The defer here would not work in the way as expected

File: zboxcore/sdk/deleteworker.go [hunk 11]
```diff
@@ -49,56 +62,91 @@ func (req *DeleteRequest) deleteBlobberFile(blobber *blockchain.StorageNode, blo
...
+		if err != nil {
+			req.maskMu.Lock()
+			req.deleteMask = req.deleteMask.And(zboxutil.NewUint128(1).Lsh(pos).Not())
+			req.maskMu.Unlock()
+		}
+	}()
+
+	fRefEntity, err = getObjectTreeFromBlobber(
+		req.ctx, req.allocationID, req.allocationTx,
+		req.remotefilepath, req.blobbers[pos])
```
Comment (peterlimg) [inline zboxcore/sdk/deleteworker.go:148]: All of the params of the function are member of req, I would suggest to just pass the req as param

File: zboxcore/sdk/deleteworker.go [hunk 12]
```diff
@@ -49,56 +62,91 @@ func (req *DeleteRequest) deleteBlobberFile(blobber *blockchain.StorageNode, blo
...
+		pos = uint64(i.TrailingZeros())
+		go func(blobberIdx uint64) {
 			defer req.wg.Done()
-			refEntity, err := req.getObjectTreeFromBlobber(req.blobbers[blobberIdx])
+			refEntity, err := req.getObjectTreeFromBlobber(blobberIdx)
 			if err == nil {
 				req.consensus.Done()
-				deleteMutex.Lock()
-				req.listMask |= (1 << uint32(blobberIdx))
 				objectTreeRefs[blobberIdx] = refEntity
```
Comment (peterlimg) [inline zboxcore/sdk/deleteworker.go:168]: objectTreeRefs[blobberIdx] may panic as the idx could be beyond the length of the slice. Imagine the the mask binary value is `100`, which mean the blobbers count is `1`, and the objectTreeRefs slice length is 1. However, the pos is 2, which will lead to panic then.

File: zboxcore/sdk/dirworker.go [hunk 13]
```diff
@@ -31,70 +30,82 @@ type DirRequest struct {
...
 
-			err := req.createDirInBlobber(a.Blobbers[blobberIdx], blobberIdx)
+			err, alreadyExists := req.createDirInBlobber(a.Blobbers[pos], pos)
 			if err != nil {
 				l.Logger.Error(err.Error())
-				return
 			}
-		}(i)
+			if alreadyExists {
+				existingDirCount++
```
Comment (peterlimg) [inline zboxcore/sdk/dirworker.go:60]: existingDirCount is not thread safe, could update it with atomic package

File: zboxcore/sdk/dirworker.go [hunk 14]
```diff
@@ -129,48 +148,59 @@ func (req *DirRequest) createDirInBlobber(blobber *blockchain.StorageNode, blobb
...
-				// should not add dirMask because there is not need to commit
-				req.mu.Unlock()
-			}
-			return errors.New(msg)
+			l.Logger.Debug(fmt.Sprintf("Got too many request error. Retrying after %d seconds", r))
+			time.Sleep(time.Duration(r) * time.Second)
+			continue
+		}
+
+		resp_body, err := ioutil.ReadAll(resp.Body)
```
Comment (peterlimg) [inline zboxcore/sdk/dirworker.go]: Use respBody

File: zboxcore/sdk/dirworker.go [hunk 15]
```diff
@@ -129,48 +148,59 @@ func (req *DirRequest) createDirInBlobber(blobber *blockchain.StorageNode, blobb
...
 
-	if err != nil {
-		return err
+		return errors.New("response_error", msg), false
+
 	}
 
-	return nil
+	return errors.New("dir_creation_failed",
+		fmt.Sprintf("Directory creation failed with response status: %d", resp.StatusCode)), false
```
Comment (peterlimg) [inline zboxcore/sdk/dirworker.go]: Seems unreachable code

File: zboxcore/sdk/listworker.go [hunk 16]
```diff
@@ -185,10 +185,10 @@ func (req *ListRequest) GetListFromBlobbers() *ListResult {
 					UpdatedAt: child.GetUpdatedAt(),
 				}
 				childResult.LookupHash = child.GetLookupHash()
+				childResult.Consensus.mu = &sync.RWMutex{}
 				childResult.consensus = 0
 				childResult.consensusThresh = req.consensusThresh
```
Comment (peterlimg) [inline zboxcore/sdk/listworker.go:190]: It would be more convenient to init consensus with a function fo newConsensus(params...) instead of assign variables one by one everywhere.

File: zboxcore/sdk/renameworker.go [hunk 17]
```diff
@@ -42,51 +42,82 @@ func (req *RenameRequest) getObjectTreeFromBlobber(blobber *blockchain.StorageNo
...
+		httpreq.Header.Add("Content-Type", formWriter.FormDataContentType())
+		ctx, cncl := context.WithTimeout(req.ctx, time.Minute)
+		resp, err = zboxutil.Client.Do(httpreq.WithContext(ctx))
+		cncl()
+
+		if err != nil {
+			logger.Logger.Error("Rename: ", err)
+			return nil, err
 		}
 		defer resp.Body.Close()
```
Comment (peterlimg) [inline zboxcore/sdk/renameworker.go]: Same as mentioned before, the defer would not work the way as expected

File: zboxcore/sdk/renameworker.go [hunk 18]
```diff
@@ -42,51 +42,82 @@ func (req *RenameRequest) getObjectTreeFromBlobber(blobber *blockchain.StorageNo
...
+
+		var respBody []byte
+		respBody, err = ioutil.ReadAll(resp.Body)
+		if err != nil {
```
Comment (peterlimg) [inline zboxcore/sdk/renameworker.go]: If http.StatusOK does not care about the resp data, this reading maybe could be avoided or maybe lead to unexpected error if the body is empty?

File: zboxcore/sdk/renameworker.go [hunk 19]
```diff
@@ -42,51 +42,82 @@ func (req *RenameRequest) getObjectTreeFromBlobber(blobber *blockchain.StorageNo
...
-	})
-	if err != nil {
-		return nil, err
+		l.Logger.Error(blobber.Baseurl, "Response: ", string(respBody))
+		err = errors.New("response_error", string(respBody))
+		return
 	}
-	return refEntity, nil
+
+	return
```
Comment (peterlimg) [inline zboxcore/sdk/renameworker.go:142]: Unreachable code

File: zboxcore/sdk/writemarker_mutex.go [hunk 20]
```diff
@@ -60,257 +52,215 @@ func CreateWriteMarkerMutex(client *client.Client, allocationObj *Allocation) (*
...
-	m.mutex.Lock()
-	defer m.mutex.Unlock()
-
-	if m.allocationObj == nil {
-		return errors.Throw(constants.ErrInvalidParameter, "allocationObj")
-	}
+func (wmMu *WriteMarkerMutex) Unlock(
+	ctx context.Context, mask zboxutil.Uint128,
+	blobbers []*blockchain.StorageNode,
+	timeOut time.Duration, connID string,
```
Comment (peterlimg) [inline zboxcore/sdk/writemarker_mutex.go:61]: The timeout could be attached to the ctx, so user could just wrap it as `ctx, cancel := context.WithTimeout(ctx, timeout)`

File: zboxcore/sdk/writemarker_mutex.go [hunk 21]
```diff
@@ -60,257 +52,215 @@ func CreateWriteMarkerMutex(client *client.Client, allocationObj *Allocation) (*
...
 
-	//retry 3 times
-	for retry := 0; ; retry++ {
-		i := 1
-		n := 0
-		m.lockedBlobbers = nil
+// Change status code to 204
+func (wmMu *WriteMarkerMutex) UnlockBlobber(
+	ctx context.Context, b *blockchain.StorageNode,
+	connID string, timeOut time.Duration, wg *sync.WaitGroup,
```
Comment (peterlimg) [inline zboxcore/sdk/writemarker_mutex.go:80]: Same as above about the timeout

File: zboxcore/sdk/writemarker_mutex.go [hunk 22]
```diff
@@ -60,257 +52,215 @@ func CreateWriteMarkerMutex(client *client.Client, allocationObj *Allocation) (*
...
-			}
+		reqCtx, ctxCncl := context.WithTimeout(ctx, timeOut)
+		resp, err = zboxutil.Client.Do(req.WithContext(reqCtx))
+		ctxCncl()
 
-			blobberIndex := i - 1
+		if err != nil {
+			return
+		}
+		if resp.StatusCode == http.StatusNoContent || resp.StatusCode == http.StatusOK {
```
Comment (peterlimg) [inline zboxcore/sdk/writemarker_mutex.go]: StatusNoContent error means the resources does not exist or not found, does that mean the lock is unlocked?

File: zboxcore/sdk/writemarker_mutex.go [hunk 23]
```diff
@@ -60,257 +52,215 @@ func CreateWriteMarkerMutex(client *client.Client, allocationObj *Allocation) (*
...
-	//retry 3 times
-	for retry := 0; ; retry++ {
-		i := 1
-		n := 0
-		m.lockedBlobbers = nil
+// Change status code to 204
+func (wmMu *WriteMarkerMutex) UnlockBlobber(
+	ctx context.Context, b *blockchain.StorageNode,
+	connID string, timeOut time.Duration, wg *sync.WaitGroup,
+) {
```
Comment (peterlimg) [inline zboxcore/sdk/writemarker_mutex.go:81]: We should not ignore the error and just log it. Any one failed below should be noted by the caller.

File: zboxcore/sdk/writemarker_mutex.go [hunk 24]
```diff
@@ -60,257 +52,215 @@ func CreateWriteMarkerMutex(client *client.Client, allocationObj *Allocation) (*
...
+		if err != nil {
+			return
+		}
+		if resp.StatusCode == http.StatusNoContent || resp.StatusCode == http.StatusOK {
+			logger.Logger.Info(b.Baseurl, connID, " unlocked")
+			return
+		}
 
-			result, err := m.lockOne(ctx, strings.NewReader(form), urls[blobberIndex])
+		if resp.StatusCode == http.StatusTooManyRequests {
```
Comment (peterlimg) [inline zboxcore/sdk/writemarker_mutex.go]: This retry code for StatusTooManyRequests is used in lot of places, it would be better to wrap the retry code into a common function so that could be reused.

File: zboxcore/sdk/writemarker_mutex.go [hunk 25]
```diff
@@ -60,257 +52,215 @@ func CreateWriteMarkerMutex(client *client.Client, allocationObj *Allocation) (*
...
+		var data []byte
+		data, err = io.ReadAll(resp.Body)
+		if err != nil {
+			return
 		}
 
-		if retry >= 2 {
-			return constants.ErrNotLockedWritMarker
+		m := string(data)
+		if m == "EOF" || strings.Contains(m, "server closed idle connection") {
```
Comment (peterlimg) [inline zboxcore/sdk/writemarker_mutex.go]: This 'server closed connection' error might be too specific, and the error could be changed as we change the ingress or upgrade the nginx. So perhaps we can just log the data directly and return instead of retry to avoid tight binding error messages.

File: zboxcore/sdk/writemarker_mutex.go [hunk 26]
```diff
@@ -60,257 +52,215 @@ func CreateWriteMarkerMutex(client *client.Client, allocationObj *Allocation) (*
...
 
-// lockOne acquire WriteMarker lock from a blobber
-func (m *WriteMarkerMutex) lockOne(ctx context.Context, body io.Reader, url string) (*WMLockResult, error) {
+}
 
-	result := &WMLockResult{}
+func (wmMu *WriteMarkerMutex) Lock(
+	ctx context.Context, mask *zboxutil.Uint128,
+	maskMu *sync.Mutex, blobbers []*blockchain.StorageNode,
+	consensus *Consensus, timeOut time.Duration, connID string) error {
```
Comment (peterlimg) [inline zboxcore/sdk/writemarker_mutex.go]: Attach the timeout to ctx

File: zboxcore/sdk/writemarker_mutex.go [hunk 27]
```diff
@@ -60,257 +52,215 @@ func CreateWriteMarkerMutex(client *client.Client, allocationObj *Allocation) (*
...
-			}
+	wg := &sync.WaitGroup{}
+	var pos uint64
+	for i := *mask; !i.Equals64(0); i = i.And(zboxutil.NewUint128(1).Lsh(pos).Not()) {
+		pos = uint64(i.TrailingZeros())
 
-			if resp.StatusCode != http.StatusOK {
-				return errors.Throw(constants.ErrNotLockedWritMarker, fmt.Sprint(resp.StatusCode, ":", string(respBody)))
-			}
+		blobber := blobbers[pos]
```
Comment (peterlimg) [inline zboxcore/sdk/writemarker_mutex.go:189]: Is it possible the blobbers[pos] panic the way I mentioned before, not sure if the blobbers are the full list of all the blobbers, if it is just the active blobbers, then it may panic.

File: zboxcore/sdk/writemarker_mutex.go [hunk 28]
```diff
@@ -60,257 +52,215 @@ func CreateWriteMarkerMutex(client *client.Client, allocationObj *Allocation) (*
...
-// Unlock release WriteMarker lock on blobbers
-func (m *WriteMarkerMutex) Unlock(ctx context.Context, connectionID string) error {
-	if m == nil {
-		return errors.Throw(constants.ErrInvalidParameter, "WriteMarkerMutex")
-	}
+// todo change blobber code as well
+func (wmMu *WriteMarkerMutex) LockBlobber(
+	ctx context.Context, mask *zboxutil.Uint128, maskMu *sync.Mutex,
+	consensus *Consensus, b *blockchain.StorageNode, pos uint64, connID string,
+	timeOut time.Duration, wg *sync.WaitGroup) {
```
Comment (peterlimg) [inline zboxcore/sdk/writemarker_mutex.go:212]: Same as above: timeout

File: zboxcore/zboxutil/http.go [hunk 29]
```diff
@@ -424,6 +425,43 @@ func NewUploadRequestWithMethod(baseURL, allocation string, body io.Reader, meth
...
+	baseURL, allocation, connID, requestTime string) (*http.Request, error) {
+
+	u := baseURL + WM_LOCK_ENDPOINT + allocation + "/" + connID
+
+	req, err := http.NewRequest(http.MethodDelete, u, nil)
+	if err != nil {
+		return nil, err
+	}
+
+	setClientInfoWithSign(req, allocation)
```
Comment (peterlimg) [inline zboxcore/zboxutil/http.go]: Check error

File: zcncore/transaction_base.go [hunk 30]
```diff
@@ -489,6 +489,9 @@ func getBlockHeaderFromTransactionConfirmation(txnHash string, cfmBlock map[stri
 
 		return nil, errors.New("", "block hash verification failed in confirmation")
 	}
+	for k, v := range cfmBlock {
+		logging.Error(k, ": ", v)
```
Comment (peterlimg) [inline zcncore/transaction_base.go]: Remove logs if it's for debugging later

**Review by peterlimg — CHANGES_REQUESTED** [review]
Please remove the empty log files

File: zcncore/transaction_base.go (hunk 30 above)
Comment (lpoli) [reply zcncore/transaction_base.go]: done

**Review by peterlimg — CHANGES_REQUESTED** [review]
Please remove `authorizer/bridge.log`

File: zboxcore/sdk/writemarker_mutex.go (hunk 26 above)
Comment (lpoli) [reply zboxcore/sdk/writemarker_mutex.go]: Actually we cannot do so.
We need to retry for 3 times. The context needs new timeout in each repetition.
Timeout is attached inside for loop

File: zboxcore/sdk/writemarker_mutex.go (hunk 27 above)
Comment (lpoli) [reply zboxcore/sdk/writemarker_mutex.go:189]: @peterlimg Yes it is full list of all the blobbers.

File: zboxcore/sdk/writemarker_mutex.go (hunk 28 above)
Comment (lpoli) [reply zboxcore/sdk/writemarker_mutex.go:212]: Timeout is attached inside for loop

File: zboxcore/zboxutil/http.go (hunk 29 above)
Comment (lpoli) [reply zboxcore/zboxutil/http.go]: done

File: zboxcore/sdk/deleteworker.go (hunk 11 above)
Comment (lpoli) [reply zboxcore/sdk/deleteworker.go:148]: We cannot do so here.
It is not a method of a same struct. It is different function

File: zboxcore/sdk/deleteworker.go (hunk 12 above)
Comment (lpoli) [reply zboxcore/sdk/deleteworker.go:168]: Yes the code is fishy. The initial mask will always contain mask for all blobbers. So it won't panic.
However I understand it is not a good practice. 

I've only kind of re-arranged logic here and there. I do understand there are so many styles that are not standard

File: zboxcore/sdk/dirworker.go (hunk 15 above)
Comment (lpoli) [reply zboxcore/sdk/dirworker.go]: It will reach if request is not successful for 3 times

File: zboxcore/sdk/copyworker.go [hunk 31]
```diff
@@ -41,107 +42,167 @@ func (req *CopyRequest) getObjectTreeFromBlobber(blobber *blockchain.StorageNode
 	return getObjectTreeFromBlobber(req.ctx, req.allocationID, req.allocationTx, req.remotefilepath, blobber)
 }
 
-func (req *CopyRequest) copyBlobberObject(blobber *blockchain.StorageNode, blobberIdx int) (fileref.RefEntity, error) {
-	refEntity, err := req.getObjectTreeFromBlobber(req.blobbers[blobberIdx])
+func (req *CopyRequest) copyBlobberObject(
+	blobber *blockchain.StorageNode, blobberIdx int) (refEntity fileref.RefEntity, err error) {
+
+	defer req.wg.Done()
```
Comment (peterlimg) [inline zboxcore/sdk/copyworker.go]: move the wg.Done outside of this function to where it is defined and avoid shared wg. This function would be misused and cause unexpected issue if the caller didn't init the wg correctly. Let's make it not that easy to go wrong.

**Review by peterlimg — CHANGES_REQUESTED** [review]
Suggest to replace the goto with closure/anonymous function to make it easy to follow.

**Review by peterlimg — APPROVED** [review]
lgtm

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/upload-issue  |
| gosdk  | fix/upload-issue  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/upload-issue  |
| gosdk  | fix/upload-issue  |
| zboxcli  | fix/upload-issue  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/upload-issue  |
| gosdk  | fix/upload-issue  |
| zboxcli  | fix/upload-issue  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/upload-issue  |
| gosdk  | fix/upload-issue  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | fix/upload-issue  |
| gosdk  | fix/upload-issue  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |
