### PR TITLE
Fix/EOF

### LINKED ISSUE #889: EOF when downloading file from blobber
File download is returning with EOF error.

**EOF** is basically responded when client uses a http connection that is closed by the server.
Its not easy to replicate this error and fix it but having connection ttl should have been fine.

Network details : 

2 Blobbers and 2 Validators 

Blobber1 : 0 read_price | 0.1 write_price
Blobber2 : 0.01 read_price | 0.1 write_price

Allocation Details : 

1 data 1 parity
1 GB size 

File Size : 0.1GB 

Both blobbers and validators are staked 1 tokens each.

### PR DESCRIPTION
**Pull request by lpoli**
### Changes
-

### Fixes
-  Tries to fix [EOF issue](https://github.com/0chain/gosdk/issues/889). The cause of EOF is unknown but it basically seems to be related to closed connection issue or issue with readLoop in net/http package. 
References:

1. https://github.com/googleapis/google-cloud-go/issues/7090
2. https://github.com/golang/go/issues/53472
3. https://stackoverflow.com/questions/17714494/golang-http-request-results-in-eof-errors-when-making-multiple-requests-successi

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

### CODE REVIEW

File: zboxcore/zboxutil/http.go [hunk 1]
```diff
@@ -741,7 +741,21 @@ func MakeSCRestAPICall(scAddress string, relativePath string, params map[string]
 func HttpDo(ctx context.Context, cncl context.CancelFunc, req *http.Request, f func(*http.Response, error) error) error {
 	// Run the HTTP request in a goroutine and pass the response to f.
 	c := make(chan error, 1)
-	go func() { c <- f(Client.Do(req.WithContext(ctx))) }()
+	go func() {
+		var err error
+		// indefinitely try if io.EOF error occurs. As per some research over google
+		// it occurs when client http tries to send byte stream in connection that is
+		// closed by the server
+		for {
```
Comment (dabasov) [inline zboxcore/zboxutil/http.go:749]: use context to break this loop and terminate goroutine properly

```
for {
    select {
        case <-ctx.Done():
             return
        default:
             //your code
    }
}
```

**Review by dabasov — CHANGES_REQUESTED** [review]

File: zboxcore/zboxutil/http.go (hunk 1 above)
Comment (lpoli) [reply zboxcore/zboxutil/http.go:749]: Context is already in use inside `client.Do` function. Only for EOF error it will continue. If it frequently shows up EOF error then it will anyway break when context timeout occurs

Comment (dabasov) [reply zboxcore/zboxutil/http.go:749]: ok, it should be enough

**Review by dabasov — APPROVED** [review]
lgtm
