### PR TITLE
Fix #399 deadlock fix

### LINKED ISSUE #399: Failed Register should also mark the status
Currently in `RegisterToMiners` if the register is successful we set the status to success but do not set the status to error when an error occurs. This leads to the wallet not being able to get out of the deadlock in a negative scenario.

### PR DESCRIPTION
**Pull request by samtholiya**
### Changes
-

### Fixes
-

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain:
- system_test:
- zboxcli:https://github.com/0chain/zboxcli/pull/183
- zwalletcli: https://github.com/0chain/zwalletcli/pull/100
- Other: ...

### CODE REVIEW

**Comment by samtholiya** [comment]
image
as seen in the above image the zbox cli is not hitting deadlock on failing to register
image

File: zcncore/wallet.go [hunk 1]
```diff
@@ -445,11 +446,12 @@ func GetNetworkJSON() string {
 
 // CreateWallet creates the wallet for to configure signature scheme.
 // It also registers the wallet again to block chain.
-func CreateWallet(statusCb WalletCallback) error {
+func CreateWallet(wg *sync.WaitGroup, statusCb WalletCallback) error {
 	if len(_config.chain.Miners) < 1 || len(_config.chain.Sharders) < 1 {
 		return errors.New("", "SDK not initialized")
 	}
 	go func() {
+		defer wg.Done()
```
Comment (cnlangzi) [inline zcncore/wallet.go]: it may not work properly. because wg.Done should already be called on statusCb.OnWalletCreateComplete.
it should be better to update WalletCallback with
```
// WalletCallback needs to be implemented for wallet creation.
type WalletCallback interface {
	OnWalletCreateComplete(status int, wallet string, err string)
        OnWalletCreateFailed(err string)
}
```
Actually , failure logic is implemented on https://github.com/0chain/zwalletcli/blob/c2e27a6101849d2e010901dab48bc82fa1a38df6/cmd/common.go#L75

**Review by cnlangzi — CHANGES_REQUESTED** [review]

File: zcncore/wallet.go [hunk 2]
```diff
@@ -445,11 +446,12 @@ func GetNetworkJSON() string {
 
 // CreateWallet creates the wallet for to configure signature scheme.
 // It also registers the wallet again to block chain.
-func CreateWallet(statusCb WalletCallback) error {
+func CreateWallet(wg *sync.WaitGroup, statusCb WalletCallback) error {
```
Comment (cnlangzi) [inline zcncore/wallet.go]:
```suggestion
func CreateWallet(statusCb WalletCallback) error {
	if len(_config.chain.Miners) < 1 || len(_config.chain.Sharders) < 1 {
		statusCb.OnWalletCreateComplete(StatusError, "", "SDK not initialized")
		return errors.New("", "SDK not initialized")
```

it should work properly

**Review by cnlangzi — CHANGES_REQUESTED** [review]

File: zcncore/wallet.go (hunk 2 above)
Comment (samtholiya) [reply zcncore/wallet.go]: i am just following this pattern so that it follows golang code pattern
This also makes sure that we handle the wg as per expectations (especially when multiple people edit the same code.

File: zcncore/wallet.go (hunk 1 above)
Comment (samtholiya) [reply zcncore/wallet.go:454]: I have changed that logic in both zwallet and zbox to reflect the changes here
to make it more as per golang language pattern expectation...

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | fix/registerFailDeadLock  |
| zboxcli  | fix/deadlock  |
| zwalletcli  | fix/gosdkupdate  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

File: zcncore/wallet.go (hunk 2 above)
Comment (cnlangzi) [reply zcncore/wallet.go]: call wg.Done multiple times, it panics there see https://github.com/0chain/gosdk/runs/5414092105?check_suite_focus=true
```
utils.go:72: panic: sync: negative WaitGroup counter
    utils.go:72: goroutine 42 [running]:
    utils.go:72: sync.(*WaitGroup).Add(0xa78860, 0xc0001193e0)
    utils.go:72: /root/actions-runner4/_work/_tool/go/1.17.2/x64/src/sync/waitgroup.go:74 +0x105
    utils.go:72: sync.(*WaitGroup).Done(0xc0001e9f18)
    utils.go:72: /root/actions-runner4/_work/_tool/go/1.17.2/x64/src/sync/waitgroup.go:99 +0x25
    utils.go:72: github.com/0chain/gosdk/zcncore.CreateWallet.func1()
    utils.go:72: /root/go/pkg/mod/github.com/0chain/gosdk@v1.7.3-0.20220303213801-9f9a89621d35/zcncore/wallet.go:466 +0xee
    utils.go:72: created by github.com/0chain/gosdk/zcncore.CreateWallet
    utils.go:72: /root/go/pkg/mod/github.com/0chain/gosdk@v1.7.3-0.20220303213801-9f9a89621d35/zcncore/wallet.go:453 +0xdb
    utils.go:72: panic: sync: WaitGroup is reused before previous Wait has returned
    utils.go:72: goroutine 1 [running]:
    utils.go:72: sync.(*WaitGroup).Wait(0xc00041c160)
    utils.go:72: /root/actions-runner4/_work/_tool/go/1.17.2/x64/src/sync/waitgroup.go:132 +0xa5
    utils.go:72: github.com/0chain/zwalletcli/cmd.initConfig()
    utils.go:72: /root/actions-runner4/_work/gosdk/gosdk/zwalletcli/cmd/root.go:142 +0xacf
    utils.go:72: github.com/spf13/cobra.(*Command).preRun(0x1301360)
    utils.go:72: /root/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:886 +0x42
    utils.go:72: github.com/spf13/cobra.(*Command).execute(0x1301360, {0xc00003a660, 0x6, 0x6})
    utils.go:72: /root/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:822 +0x1db
    utils.go:72: github.com/spf13/cobra.(*Command).ExecuteC(0x1301d60)
    utils.go:72: /root/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
    utils.go:72: github.com/spf13/cobra.(*Command).Execute(...)
    utils.go:72: /root/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
    utils.go:72: github.com/0chain/zwalletcli/cmd.Execute()
    utils.go:72: /root/actions-runner4/_work/gosdk/gosdk/zwalletcli/cmd/root.go:47 +0x25
    utils.go:72: main.main()
    utils.go:72: /root/actions-runner4/_work/gosdk/gosdk/zwalletcli/main.go:11 +0x4a
    zwalletcli_send_and_balance_test.go:417: 
        	Error Trace:	zwalletcli_send_and_balance_test.go:417
        	            				0_zwalletcli_miner_update_settings_test.go:22
        	Error:      	Expected nil, but got: &exec.ExitError{ProcessState:(*os.ProcessState)(0xc00020c2b8), Stderr:[]uint8(nil)}
        	Test:       	TestMinerUpdateSettings
        	Messages:   	get miners sc config failed%!(EXTRA string=No wallet in path  ./con
```

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | fix/registerFailDeadLock  |
| zboxcli  |  fix/deadlock  |
| zwalletcli  | fix/gosdkupdate  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by cnlangzi — APPROVED** [review]
LGTM
