### PR TITLE
Fix: subgraph initialization

### LINKED ISSUE #903: Fix: subgraph initialization

### PR DESCRIPTION
**Pull request by YarikRevich**
## Associated PRs
* https://github.com/0chain/token_bridge_authserver/pull/74

### CODE REVIEW

File: zcnbridge/bridge.go [hunk 1]
```diff
@@ -332,6 +332,11 @@ func (b *BridgeClient) GetNotProcessedWZCNBurnTickets(ctx context.Context, mintN
 		return nil, errors.New("DefaultClientIDEncoder must be setup")
 	}
 
+	graphQlClient, err := b.CreateSubgraphClient()
```
Comment (dabasov) [inline zcnbridge/bridge.go]: please do not expose graphql to clients and move this service to authorizers

**Review by dabasov — CHANGES_REQUESTED** [review]

**Review by dabasov — APPROVED** [review]
lgtm

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | master  |
| gosdk  | feature/graphql_switch  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |
