### PR TITLE
Fix: bridge "burnZCN" in wasm

### LINKED ISSUE #680: Fix: bridge "burnZCN" in wasm

### PR DESCRIPTION
**Pull request by YarikRevich**

### CODE REVIEW

File: wasmsdk/bridge.go [hunk 1]
```diff
@@ -68,11 +68,20 @@ func initBridge(
...
+		return errors.New("burnZCN", "bridge is not initialized").Error()
+	}
+
 	tx, err := bridge.BurnZCN(context.Background(), amount)
 	if err != nil {
 		return errors.Wrap("burnZCN", "failed to burn ZCN tokens", err).Error()
 	}
-	
+
+	err = tx.Verify(context.Background())
```
Comment (dabasov) [inline wasmsdk/bridge.go]: I think we should verify inside `bridge.BurnZCN`

**Review by dabasov — CHANGES_REQUESTED** [review]

**Review by dabasov — APPROVED** [review]
lgtm

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | YES  |
| system-tests  | master  |
| gosdk  | fix/bridge_burn_zcn_wasm  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |
