### PR TITLE
fix caching for fees table

### LINKED ISSUE #1112: Transaction fee cache issue in wasm
Currently we store the estimated transaction fee in a global cache, and the cached value will be used as the fee next time when new transaction is about to be submitted. So if we run any txn 0 fee such as faucet pour SC first, the cached the fee will be `0`, therefore if we try to do another transaction such as create new allocation transaction, the fee of value `0` will be used and we will failed to send the transaction. zboxcli and zwallet may not have the issue as the cache is fresh in each run of the command, but seems wasm will have problem as the cache persist before the webpage is reloaded.  @dabasov @boddumanohar please help to. check if this is true.

### PR DESCRIPTION
**Pull request by boddumanohar**
### Changes
-

### Fixes
-

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

### CODE REVIEW

File: core/transaction/entity.go [hunk 1]
```diff
@@ -290,112 +290,55 @@ type cachedObject struct {
...
+	txData := txn.TransactionData
 
-			url := minerUrl + ESTIMATE_TRANSACTION_COST
-			req, err := util.NewHTTPPostRequest(url, txn)
-			if err != nil {
-				errC <- fmt.Errorf("create request failed, url: %s, err: %v", url, err)
-				return
-			}
+	var sn SmartContractTxnData
+	json.Unmarshal([]byte(txData), &sn)
```
Comment (dabasov) [inline core/transaction/entity.go]: please handle the error

**Review by dabasov — CHANGES_REQUESTED** [review]

File: core/transaction/entity.go (hunk 1 above)
Comment (boddumanohar) [reply core/transaction/entity.go]: fixed in 38b9f59

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  |   |
| gosdk  | fix-fees  |
| zboxcli  |   |
| zwalletcli  |   |
| 0chain  |   |
| blobber  |   |
| authorizer  |   |
| 0box  |   |
| 0dns  |   |

**Review by dabasov — COMMENTED** [review]
lgtm
