### PR TITLE
fixes for update image

### LINKED ISSUE #1054: `createAllocation` doesn’t respect the preferred blobbers sent over by the client
Ref: https://0chain.slack.com/archives/C03HUFQD01M/p1687195937985649

### PR DESCRIPTION
**Pull request by boddumanohar**
### Changes

1. the actual portainer URL should be passed here. meaning: for blobber: https://chimneyr58xb.zus.network/portainer  and for miner/sharder it will be: https://portainer.dev3.zus.network
2. in search container: the full container name should be passed.
     In case of blobber blobber_blobber
     in case of validator validator_validator
    in case of miner miner
    in case of sharder sharder

3. preserver order in blobber of newallocationrequestg
4. added demo for multi operation
5. initialised Consensus in Lock Request
6. wasm feat: updateForbidAllocation
7. expose lockReadPool

### Fixes
-

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

### CODE REVIEW

File: wasmsdk/allocation.go [hunk 1]
```diff
@@ -104,6 +104,32 @@ func transferAllocation(allocationID, newOwnerId, newOwnerPublicKey string) erro
 	return err
 }
 
+// updateForbidAllocation updates the settings for forbid alocation
+func UpdateForbidAllocation(allocationID string, forbidupload, forbiddelete, forbidupdate, forbidmove, forbidcopy, forbidrename bool) (string, error) {
+
+	hash, _, err := sdk.UpdateAllocation(
+		0,            //size,
```
Comment (dabasov) [inline wasmsdk/allocation.go:111]: you can avoid setting default values

**Review by dabasov — APPROVED** [review]
lgtm
