### PR TITLE
fix(mobile): improved redeemFreeStorage 

### LINKED ISSUE #585: update: mobilesdk redeemFreeStorage
`redeemFreeStorage` method does not throw errors when allocation creation fails, hence frontend is not notified of failure. proposed solution is to either update the error handling to send errors if the smart contract fails, or to have a callback similar to `onWalletCreateComplete`.

### PR DESCRIPTION
**Pull request by cnlangzi**
### Changes
-

### Fixes
- fixed https://github.com/0chain/gosdk/issues/585 

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
-

### CODE REVIEW

File: zcncore/transaction_mobile.go [hunk 1]
```diff
@@ -1105,9 +1104,14 @@ func (t *Transaction) ZCNSCAddAuthorizer(ip AddAuthorizerPayload) (err error) {
 	return
 }
 
+// ConvertToTokenValue converts ZCN tokens to value
+func ConvertToTokenValue(token float64) uint64 {
```
Comment (peterlimg) [inline zcncore/transaction_mobile.go]: sshould be ConvertTokenToSAS, 1 ZCN token = 1e10 SAS.

**Review by peterlimg — CHANGES_REQUESTED** [review]

File: zcncore/transaction_mobile.go (hunk 1 above)
Comment (cnlangzi) [reply zcncore/transaction_mobile.go]: fixed

**Review by peterlimg — APPROVED** [review]
lgtm
