### PR TITLE
Fix/refactor zboxcore and zcncore

### LINKED ISSUE #1584: Fix/refactor zboxcore

### PR DESCRIPTION
**Pull request by Jayashsatolia403**
### Changes
-

### Fixes
-

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

### CODE REVIEW

File: zcnbridge/transaction/functions.go [hunk 1]
```diff
@@ -2,62 +2,58 @@ package transaction
...
-	t.SetHash(scheme.Hash())
-	if err != nil {
-		return t, err
-	}
-
-	return t, nil
-}
+//JAYASHTODO : Uncomment if possible or rewrite
+
+//// AddAuthorizer adds authorizer to the bridge
```
Comment (dabasov) [inline zcnbridge/transaction/functions.go]: delete or uncomment

**Review by dabasov — CHANGES_REQUESTED** [review]

**Review by dabasov — APPROVED** [review]
lgtm
