### PR TITLE
Fix/concurrent operation issue

### LINKED ISSUE #695: Concurrent operations on allocations are flaky
image

Test; TestFileRename/Rename_and_delete_file_concurrently,_should_work

Note: This is not limited to rename and delete, it happens in other concurrent CRUD operations

### PR DESCRIPTION
**Pull request by lpoli**
### Changes
- Add a goroutine that checks if lock is about to expire then refresh the lock.

### Fixes
- Fix writemarker commits issue after lock expires and another process acquires the lock

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber: https://github.com/0chain/blobber/pull/931
- 0chain:
- system_test:
- zboxcli: https://github.com/0chain/zboxcli/pull/347
- zwalletcli:
- Other: ...

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | fix/concurrent-operation-issue  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/concurrent-operation-issue  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | fix/concurrent-operation-issue  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/concurrent-operation-issue  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

File: zboxcore/sdk/writemarker_mutex.go [hunk 1]
```diff
@@ -315,9 +330,19 @@ func (wmMu *WriteMarkerMutex) LockBlobber(
...
-			continue
+		if !shouldContinue {
+			break
 		}
-		return
 	}
+
+	go func() {
+		for {
+			d := time.Since(requestTime)
```
Comment (dabasov) [inline zboxcore/sdk/writemarker_mutex.go]: we should avoid such a recursions, when it can exit?

**Review by dabasov — CHANGES_REQUESTED** [review]

File: zboxcore/sdk/writemarker_mutex.go (hunk 1 above)
Comment (lpoli) [reply zboxcore/sdk/writemarker_mutex.go]: It will run wmMu.LockBlobber and return immediately and so for loop is terminated. If the ctx is done then it will exit. In Line 218 it is waiting on ctx.Done.

If context is not done yet, it will refresh lock.

Comment (dabasov) [reply zboxcore/sdk/writemarker_mutex.go]: this logic looks fuzzy, let's change recursion to the controlled loop, make several attempts to lock and then exit

**Review by dabasov — APPROVED** [review]
lgtm
