### PR TITLE
Fix: remove client_id field from mintWZCN

### LINKED ISSUE #635: Fix: remove "client_id" field from zcnbridge

### PR DESCRIPTION
**Pull request by YarikRevich**
Refers to issue #635

### CODE REVIEW

File: zcnbridge/authorizer_response.go [hunk 1]
```diff
@@ -35,12 +35,11 @@ type (
 
 	// ProofZCNBurn Authorizer returns this type for ZCN transaction
 	ProofZCNBurn struct {
```
Comment (dabasov) [inline zcnbridge/authorizer_response.go:37]: address we are burning for is missing

File: zcnbridge/authorizers_query.go [hunk 2]
```diff
@@ -93,11 +93,10 @@ func (b *BridgeClient) QueryEthereumMintPayload(zchainBurnHash string) (*ethereu
 		}
 
 		payload := &ethereum.MintPayload{
```
Comment (dabasov) [inline zcnbridge/authorizers_query.go:95]: address we are burning for is missing

**Review by dabasov — CHANGES_REQUESTED** [review]

**Review by dabasov — APPROVED** [review]
lgtm
