### PR TITLE
Fix lockBlobber sleep

### LINKED ISSUE #879: Need a better way to implement lockBlobber function in writemarker_mutex.go
In the current implementation of [lockBlobber](https://github.com/0chain/gosdk/blob/eb0f6b0a69d87c034a1948c5bafd0aa8fab64e81/zboxcore/sdk/writemarker_mutex.go#L242), if the blobbers are locked, then the current request goes to sleep for `2*timeout` time, so when it again make a request, then blobbers are returning a timeout error. 
This would create a problem if we wanted to upload/update multiple files parallelly through the `sync` command. 
We need to correct this before closing [#100](https://github.com/0chain/zboxcli/issues/100)

https://github.com/0chain/gosdk/blob/eb0f6b0a69d87c034a1948c5bafd0aa8fab64e81/zboxcore/sdk/writemarker_mutex.go#L316

### PR DESCRIPTION
**Pull request by Roshan-Mehta**
### Changes
- Decreased sleep time if the blobber is already locked.
- Try indefinitely if the lock status is pending

### Fixes
- Fix https://github.com/0chain/gosdk/issues/879

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

### CODE REVIEW

File: zboxcore/sdk/writemarker_mutex.go [hunk 1]
```diff
@@ -313,7 +313,7 @@ func (wmMu *WriteMarkerMutex) lockBlobber(
 				if wmLockRes.Status == WMLockStatusPending {
 					logger.Logger.Info("Lock pending for blobber ",
 						b.Baseurl, "with connection id: ", connID, " Retrying again")
-					time.Sleep(timeOut * 2)
+					time.Sleep(5 * time.Second)  // sleep for 5 seconds
```
Comment (lpoli) [inline zboxcore/sdk/writemarker_mutex.go]: Please use constant variable to declare this duration.
Also is it only the place that requires this change?

**Review by lpoli — CHANGES_REQUESTED** [review]

File: zboxcore/sdk/writemarker_mutex.go (hunk 1 above)
Comment (Roshan-Mehta) [reply zboxcore/sdk/writemarker_mutex.go]: @lpoli  
`Also is it only the place that requires this change?`
The other potential place is [this](https://github.com/0chain/gosdk/blob/a902336c8a93df9eee5daac96244ebbdb849f0ad/zboxcore/sdk/writemarker_mutex.go#L326), where `resp.StatusCode == http.StatusAccepted`, but I couldn't reproduce this response from blobber, so can't comment much. Shall I change this also?

File: zboxcore/sdk/writemarker_mutex.go [hunk 2]
```diff
@@ -363,6 +363,7 @@ func (wmMu *WriteMarkerMutex) lockBlobber(
 		if !shouldContinue {
 			break
 		}
+		WMLockWaitTime *= 2 //In each round we increase the wait time by factor 2.
```
Comment (Roshan-Mehta) [inline zboxcore/sdk/writemarker_mutex.go]: Instead of fix wait time, we are increasing wait time
by factor 2 and starting with low wait time. When there are multiple
goroutines (say n)  trying to lock Blobber, then we no longer need to wait
O(n * wait_time) time.

Comment (lpoli) [reply zboxcore/sdk/writemarker_mutex.go]: Lets not make WMLockWaitTime a variable instead make it constant.
Waittime is increasing at some condition and never decreasing.
For simplicity lets put:
`const WMLockWaitTime = time.Second * 5`
To wait simply multiply it by some factor but never update the value

**Review by lpoli — CHANGES_REQUESTED** [review]

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | fix/lock-blobber-sleep  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

File: zboxcore/sdk/writemarker_mutex.go [hunk 3]
```diff
@@ -242,7 +243,7 @@ func (wmMu *WriteMarkerMutex) Lock(
 func (wmMu *WriteMarkerMutex) lockBlobber(
 	ctx context.Context, mask *zboxutil.Uint128, maskMu *sync.Mutex,
 	consensus *Consensus, b *blockchain.StorageNode, pos uint64, connID string,
-	requestTime string, timeOut time.Duration, wg *sync.WaitGroup) {
+	requestTime *string, timeOut time.Duration, wg *sync.WaitGroup) {
```
Comment (lpoli) [inline zboxcore/sdk/writemarker_mutex.go]: Why do we need to send requestTime pointer?

Comment (Roshan-Mehta) [reply zboxcore/sdk/writemarker_mutex.go]: Because we are refreshing the lock after every 20 seconds in Lock() function. So, Lock() function needs to know the requestTime.

Comment (lpoli) [reply zboxcore/sdk/writemarker_mutex.go]: The request time was already being updated in line 224 so we do not need to update it in line 278.
And Lock() function does not need to know about request time, though irrelevant to the usecase

Comment (Roshan-Mehta) [reply zboxcore/sdk/writemarker_mutex.go:246]: Yes, correct. I think I need to send the pointer of "requestTime" from the Lock() function and not the pointer of "rT".

Comment (Roshan-Mehta) [reply zboxcore/sdk/writemarker_mutex.go]: We need to send requestTime as a pointer. Let's say From Lock() function, there is a call to lockBlobber at some time (say at the 0th second), but the lock is acquired at the 15th second, so the lock should refresh at the 35th second (after the 20th second of lock acquired). So, my point is Lock() function should know when the lock is actually acquired by LockBlobber().

Comment (Roshan-Mehta) [reply zboxcore/sdk/writemarker_mutex.go]: Anyway, we are removing request time (https://github.com/0chain/gosdk/pull/926), so it doesn't matter now.

**Comment by dabasov** [comment]
we won't use request marker in lock request

File: zboxcore/sdk/writemarker_mutex.go [hunk 4]
```diff
@@ -308,21 +309,15 @@ func (wmMu *WriteMarkerMutex) lockBlobber(
...
+					time.Sleep(WMLockWaitTime)
 					shouldContinue = true
+					retry--
 					return
 				}
 				err = fmt.Errorf("Lock acquiring failed")
 				return
 			}
 
-			if resp.StatusCode == http.StatusAccepted { // accepted but pending
```
Comment (peterlimg) [inline zboxcore/sdk/writemarker_mutex.go:319]: We should keep the code for processing the `StatusAccepted`, we need to wait and retry, otherwise, we will try to read body from the response and return error, which is not what expected.

**Review by peterlimg — CHANGES_REQUESTED** [review]

File: zboxcore/sdk/writemarker_mutex.go (hunk 4 above)
Comment (Roshan-Mehta) [reply zboxcore/sdk/writemarker_mutex.go:319]: @peterlimg Does the blobber return StatusAccepted ever? I saw the blobber code and couldn't find it. Can you point to the file?

Comment (peterlimg) [reply zboxcore/sdk/writemarker_mutex.go:319]: @Roshan-Mehta yes, you're right, the blobber does not return StatusAccepted code, don't know why it checks it here before. So should be safe to remove it.

**Review by peterlimg — APPROVED** [review]
LGTM
