### PR TITLE
Change key of read counter and check for nil value

### LINKED ISSUE #548: Disallow `GetAllocation` call after it is first called
```
{"log":"0box-sdk: [INFO]   2022/08/16 21:19:46.927817 copyworker.go:154: Commit successhttps://blobber.devnet-0chain.net/blobber17\n","stream":"stderr","time":"2022-08-16T21:19:46.927845228Z"}
{"log":"fatal error: sync: Unlock of unlocked RWMutex\n","stream":"stderr","time":"2022-08-16T21:19:46.928897669Z"}
{"log":"\n","stream":"stderr","time":"2022-08-16T21:19:47.014063276Z"}
{"log":"goroutine 733210 [running]:\n","stream":"stderr","time":"2022-08-16T21:19:47.014083715Z"}
{"log":"runtime.throw({0xde9ba4?, 0x290000c0028c1000?})\n","stream":"stderr","time":"2022-08-16T21:19:47.014088905Z"}
{"log":"\u0009/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc005a8ad38 sp=0xc005a8ad08 pc=0x455651\n","stream":"stderr","time":"2022-08-16T21:19:47.014093495Z"}
{"log":"sync.throw({0xde9ba4?, 0x0?})\n","stream":"stderr","time":"2022-08-16T21:19:47.014098425Z"}
{"log":"\u0009/usr/local/go/src/runtime/panic.go:978 +0x1e fp=0xc005a8ad58 sp=0xc005a8ad38 pc=0x48081e\n","stream":"stderr","time":"2022-08-16T21:19:47.014102844Z"}
{"log":"sync.(*RWMutex).Unlock(0xc008ecc450)\n","stream":"stderr","time":"2022-08-16T21:19:47.014107464Z"}
{"log":"\u0009/usr/local/go/src/sync/rwmutex.go:201 +0x4a fp=0xc005a8ad90 sp=0xc005a8ad58 pc=0x490eaa\n","stream":"stderr","time":"2022-08-16T21:19:47.014111874Z"}
{"log":"github.com/0chain/gosdk/zboxcore/sdk.setBlobberReadCtr(0xc00284e900, 0x46)\n","stream":"stderr","time":"2022-08-16T21:19:47.014120644Z"}
{"log":"\u0009/go/pkg/mod/github.com/0chain/gosdk@v1.8.7-0.20220812132901-988ed81d68cd/zboxcore/sdk/read_counter_ctr.go:27 +0x65 fp=0xc005a8adc0 sp=0xc005a8ad90 pc=0x9a5045\n","stream":"stderr","time":"2022-08-16T21:19:47.014125484Z"}
{"log":"github.com/0chain/gosdk/zboxcore/sdk.(*BlockDownloadRequest).downloadBlobberBlock.func1(0xc00a220630, {0x0?, 0x0?})\n","stream":"stderr","time":"2022-08-16T21:19:47.014130594Z"}
```

### PR DESCRIPTION
**Pull request by lpoli**
### Fixes
This PR will fix lock/unlock panic issue that occurs when `InitAllocation` is called while read counter has acquired lock.

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

### CODE REVIEW

File: zboxcore/sdk/read_counter_ctr.go [hunk 1]
```diff
@@ -2,40 +2,43 @@ package sdk
...
+		brc = &blobberReadCounter{
+			m:  make(map[string]int64),
+			mu: &sync.RWMutex{},
+		}
 	}
 
 }
 
-func setBlobberReadCtr(blobber *blockchain.StorageNode, ctr int64) {
+func setBlobberReadCtr(clientID, blobberID string, ctr int64) {
```
Comment (avanaur) [inline zboxcore/sdk/read_counter_ctr.go]: can this be allocationID + blobberID instead? 
gosdk can be initialized with one wallet so it would always be same client. But gosdk can work on many allocations.

File: zboxcore/sdk/read_counter_ctr.go [hunk 2]
```diff
@@ -2,40 +2,43 @@ package sdk
...
+	key := clientID + blobberID
 	brc.mu.Lock()
-	brc.m[blobber.ID] = ctr
+	brc.m[key] = ctr
 	brc.mu.Unlock()
 }
 
-func getBlobberReadCtr(blobber *blockchain.StorageNode) int64 {
+func getBlobberReadCtr(clientID, blobberID string) int64 {
+	key := clientID + blobberID
```
Comment (avanaur) [inline zboxcore/sdk/read_counter_ctr.go]: Perhaps with ":" separator?

File: zboxcore/sdk/read_counter_ctr.go [hunk 3]
```diff
@@ -2,40 +2,43 @@ package sdk
...
-	"github.com/0chain/gosdk/zboxcore/blockchain"
 )
 
 type blobberReadCounter struct {
 	m  map[string]int64
 	mu *sync.RWMutex
 }
 
-var brc blobberReadCounter
+var brc *blobberReadCounter
```
Comment (avanaur) [inline zboxcore/sdk/read_counter_ctr.go]: Can we just go with this so no need for `InitReadCounter` func?
```suggestion
var brc = &blobberReadCounter{
  m:  make(map[string]int64),
  mu: &sync.RWMutex{},
}
```

File: zboxcore/sdk/read_counter_ctr.go (hunk 1 above)
Comment (lpoli) [reply zboxcore/sdk/read_counter_ctr.go]: It actually is a good point.

File: zboxcore/sdk/read_counter_ctr.go (hunk 2 above)
Comment (lpoli) [reply zboxcore/sdk/read_counter_ctr.go]: Yes but its redundant. ":" would be good if it was for display purpose.
Why add a byte if without it, it works fine.

**Review by avanaur — APPROVED** [review]
LGTM
