### PR TITLE
Correct failure reason for the duplicate file upload 

### LINKED ISSUE #690: (error msg) downloadThumbnail method error File content didn't match with uploaded file
gosdk downloadThumbnail method error return this error: 

` File content didn't match with uploaded file`
We can think it doesn’t have thumbnail if download thumbnail doesn’t work. Error message needs to be updated.

### PR DESCRIPTION
**Pull request by Manish-210**
### Changes
-Using two channels one for the error message and other for the waitgroup in the chunked upload file to show correct error message to the user. 

### Fixes
-https://github.com/0chain/zboxcli/issues/327

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

### CODE REVIEW

File: zboxcore/sdk/chunked_upload.go [hunk 1]
```diff
@@ -594,12 +597,24 @@ func (su *ChunkedUpload) processUpload(chunkStartIndex, chunkEndIndex int,
...
+	go func() {
+		wg.Wait()
+		close(wgDone)
+	}()
+	
+	select {
+		case <-wgDone:
+			break
+		case err := <-wgErrors:
+			close(wgErrors)
```
Comment (peterlimg) [inline zboxcore/sdk/chunked_upload.go]: `wgErrors <- err` in line 600 above will panic in another goroutine after we close the `wgErrors` here. We should only close on data writer rather than the reader. Anyway, to fix it and avoid goroutine leak, we can use `select` in line 600, and remove the `close(wgErrors)` here.
```go
select {
wgErrors <- err:
default:
}
```

**Review by peterlimg — CHANGES_REQUESTED** [review]

File: zboxcore/sdk/chunked_upload.go (hunk 1 above)
Comment (Manish-210) [reply zboxcore/sdk/chunked_upload.go]: Thanks for the input @peterlimg. Understood why the panic will happen and corrected the code accordingly.

File: zboxcore/sdk/chunked_upload.go [hunk 2]
```diff
@@ -594,12 +597,27 @@ func (su *ChunkedUpload) processUpload(chunkStartIndex, chunkEndIndex int,
 			defer wg.Done()
 			err = b.sendUploadRequest(ctx, su, chunkEndIndex, isFinal, encryptedKey, body, formData, pos)
 			if err != nil {
+				select {
+					case wgErrors <- err:
```
Comment (dabasov) [inline zboxcore/sdk/chunked_upload.go:601]: what is the reason for this select? is it the same as next `wgErrors <- err` write?

**Review by dabasov — CHANGES_REQUESTED** [review]

File: zboxcore/sdk/chunked_upload.go (hunk 2 above)
Comment (peterlimg) [reply zboxcore/sdk/chunked_upload.go:601]: @Manish-210 may forget to remove the `wgErrors <- err` below

File: zboxcore/sdk/chunked_upload.go [hunk 3]
```diff
@@ -594,12 +597,27 @@ func (su *ChunkedUpload) processUpload(chunkStartIndex, chunkEndIndex int,
...
+					default:
+				}
+				wgErrors <- err
```
Comment (peterlimg) [inline zboxcore/sdk/chunked_upload.go]: @Manish-210 please remove this `wgErrors <- err`, it will cause the goroutine stuck.

**Review by peterlimg — CHANGES_REQUESTED** [review]

File: zboxcore/sdk/chunked_upload.go (hunk 2 above)
Comment (Manish-210) [reply zboxcore/sdk/chunked_upload.go:601]: Sorry I forgot to remove it on line 604. Thanks @peterlimg & @dabasov for pointing it out.

File: zboxcore/sdk/chunked_upload.go (hunk 3 above)
Comment (Manish-210) [reply zboxcore/sdk/chunked_upload.go]: Corrected.

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | correct_upload_failure_reason  |
| gosdk  | correct_failure_reason  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by peterlimg — APPROVED** [review]
LGTM

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | correct_upload_failure_reason  |
| gosdk  | correct_failure_reason  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by dabasov — APPROVED** [review]
